# Python Data preprocessing - Code Examples

## 1.0 Identifying missing values in tabular data

In [5]:
import numpy as np
import pandas as pd
from io import StringIO

# Create dummy dataset for training
csv_data = \
'''A,B,C,D
 1.0, 2.0,3.0,4.0
 5.0, 6.0,,9.0
 6.0, 7.0,,10.0
 7.0, 8.0,9.0,11.0
 8.0, 9.0,,
 9.0,10.0,11.0,
15.0,11.0,,14.0
16.0,12.0,13.0,
17.0,13.0,,16.0
18.0,14.0,15.0,17.0
20.0,15.0,18.0,'''

df = pd.read_csv(StringIO(csv_data))
df

A     B     C     D
0    1.0   2.0   3.0   4.0
1    5.0   6.0   NaN   9.0
2    6.0   7.0   NaN  10.0
3    7.0   8.0   9.0  11.0
4    8.0   9.0   NaN   NaN
5    9.0  10.0  11.0   NaN
6   15.0  11.0   NaN  14.0
7   16.0  12.0  13.0   NaN
8   17.0  13.0   NaN  16.0
9   18.0  14.0  15.0  17.0
10  20.0  15.0  18.0   NaN

In [3]:
# get the overview of the dataset
df.describe()

A          B          C          D
count  11.000000  11.000000   6.000000   7.000000
mean   11.090909   9.727273  11.500000  11.571429
std     6.300072   3.849439   5.205766   4.503967
min     1.000000   2.000000   3.000000   4.000000
25%     6.500000   7.500000   9.500000   9.500000
50%     9.000000  10.000000  12.000000  11.000000
75%    16.500000  12.500000  14.500000  15.000000
max    20.000000  15.000000  18.000000  17.000000

In [5]:
# Find out number of missing values in the dataset
df.isnull().sum()

A    0
B    0
C    5
D    4
dtype: int64

In [7]:
# Find out the values that are in the numpy array to inform missing values
# (access the underlying NumPy array via the `values` attribute)
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  9.],
       [ 6.,  7., nan, 10.],
       [ 7.,  8.,  9., 11.],
       [ 8.,  9., nan, nan],
       [ 9., 10., 11., nan],
       [15., 11., nan, 14.],
       [16., 12., 13., nan],
       [17., 13., nan, 16.],
       [18., 14., 15., 17.],
       [20., 15., 18., nan]])

## 2.0 Eliminating training samples or features with missing values

In [9]:
# Find out which rows don't have missing values
df.dropna(axis=0)

A     B     C     D
0   1.0   2.0   3.0   4.0
3   7.0   8.0   9.0  11.0
9  18.0  14.0  15.0  17.0

In [11]:
# Find out which columns don't have missing values
df.dropna(axis=1)

A     B
0    1.0   2.0
1    5.0   6.0
2    6.0   7.0
3    7.0   8.0
4    8.0   9.0
5    9.0  10.0
6   15.0  11.0
7   16.0  12.0
8   17.0  13.0
9   18.0  14.0
10  20.0  15.0

In [13]:
# How to drop rows where all columns are NaN
df.dropna(how='all')

A     B     C     D
0    1.0   2.0   3.0   4.0
1    5.0   6.0   NaN   9.0
2    6.0   7.0   NaN  10.0
3    7.0   8.0   9.0  11.0
4    8.0   9.0   NaN   NaN
5    9.0  10.0  11.0   NaN
6   15.0  11.0   NaN  14.0
7   16.0  12.0  13.0   NaN
8   17.0  13.0   NaN  16.0
9   18.0  14.0  15.0  17.0
10  20.0  15.0  18.0   NaN

In [15]:
# drop rows that have fewer than 3 real values 
df.dropna(thresh=3)

A     B     C     D
0    1.0   2.0   3.0   4.0
1    5.0   6.0   NaN   9.0
2    6.0   7.0   NaN  10.0
3    7.0   8.0   9.0  11.0
5    9.0  10.0  11.0   NaN
6   15.0  11.0   NaN  14.0
7   16.0  12.0  13.0   NaN
8   17.0  13.0   NaN  16.0
9   18.0  14.0  15.0  17.0
10  20.0  15.0  18.0   NaN

In [17]:
# only drop rows where NaN appear in specific columns (here: 'D')
df.dropna(subset=['D'])

A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0   NaN   9.0
2   6.0   7.0   NaN  10.0
3   7.0   8.0   9.0  11.0
6  15.0  11.0   NaN  14.0
8  17.0  13.0   NaN  16.0
9  18.0  14.0  15.0  17.0

## 3.0 Imputing missing values

In [ ]:
# again: original array
df.values

In [19]:
# Find out column stats
print(df.mean())
print(df.median())

A    11.090909
B     9.727273
C    11.500000
D    11.571429
dtype: float64
A     9.0
B    10.0
C    12.0
D    11.0
dtype: float64


In [33]:
# impute missing values via the column mean
from sklearn.impute import SimpleImputer

imr_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imr_mean.fit(df.values)
mean_imputed_data = imr_mean.transform(df.values)
mean_imputed_data


array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        , 11.5       ,  9.        ],
       [ 6.        ,  7.        , 11.5       , 10.        ],
       [ 7.        ,  8.        ,  9.        , 11.        ],
       [ 8.        ,  9.        , 11.5       , 11.57142857],
       [ 9.        , 10.        , 11.        , 11.57142857],
       [15.        , 11.        , 11.5       , 14.        ],
       [16.        , 12.        , 13.        , 11.57142857],
       [17.        , 13.        , 11.5       , 16.        ],
       [18.        , 14.        , 15.        , 17.        ],
       [20.        , 15.        , 18.        , 11.57142857]])

In [35]:
# impute missing values via the column median
imr_median = SimpleImputer(missing_values=np.nan, strategy='median')
imr_median.fit(df.values)
median_imputed_data = imr_mean.transform(df.values)
median_imputed_data


array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        , 11.5       ,  9.        ],
       [ 6.        ,  7.        , 11.5       , 10.        ],
       [ 7.        ,  8.        ,  9.        , 11.        ],
       [ 8.        ,  9.        , 11.5       , 11.57142857],
       [ 9.        , 10.        , 11.        , 11.57142857],
       [15.        , 11.        , 11.5       , 14.        ],
       [16.        , 12.        , 13.        , 11.57142857],
       [17.        , 13.        , 11.5       , 16.        ],
       [18.        , 14.        , 15.        , 17.        ],
       [20.        , 15.        , 18.        , 11.57142857]])

In [37]:
# impute missing values using LOCF
df.ffill().values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  3.,  9.],
       [ 6.,  7.,  3., 10.],
       [ 7.,  8.,  9., 11.],
       [ 8.,  9.,  9., 11.],
       [ 9., 10., 11., 11.],
       [15., 11., 11., 14.],
       [16., 12., 13., 14.],
       [17., 13., 13., 16.],
       [18., 14., 15., 17.],
       [20., 15., 18., 17.]])

In [27]:
# impute missing values using NOCB
df.bfill().values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  9.,  9.],
       [ 6.,  7.,  9., 10.],
       [ 7.,  8.,  9., 11.],
       [ 8.,  9., 11., 14.],
       [ 9., 10., 11., 14.],
       [15., 11., 13., 14.],
       [16., 12., 13., 16.],
       [17., 13., 15., 16.],
       [18., 14., 15., 17.],
       [20., 15., 18., nan]])

## 4.0 Handling categorical data

### 4.1. Nominal and ordinal features

In [7]:
# create dummy dataset for categorial data
df = pd.DataFrame([['green', 'M', 10.1, 'sweatshirt'],
                   ['red',   'L', 13.5, 't-shirt'],
                   ['white', 'S', 13.5, 't-shirt'],
                   ['yellow','M', 13.5, 'sweatshirt'],
                   ['pink',  'M', 13.5, 'sweatshirt'],
                   ['black', 'S', 13.5, 't-shirt'],
                   ['grey',  'S', 13.5, 't-shirt'],
                   ['grey',  'S', 13.5, 'pullover'],
                   ['grey',  'L', 13.5, 't-shirt'],
                   ['orange','M', 13.5, 'pullover'],
                   ['lila',  'L', 13.5, 'pullover'],
                   ['blue', 'XL', 15.3, 'pullover']])

df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price  classlabel
0    green    M   10.1  sweatshirt
1      red    L   13.5     t-shirt
2    white    S   13.5     t-shirt
3   yellow    M   13.5  sweatshirt
4     pink    M   13.5  sweatshirt
5    black    S   13.5     t-shirt
6     grey    S   13.5     t-shirt
7     grey    S   13.5    pullover
8     grey    L   13.5     t-shirt
9   orange    M   13.5    pullover
10    lila    L   13.5    pullover
11    blue   XL   15.3    pullover

In [9]:
# Find out different categories in the dataset
print(df['color'].unique())
print(df['size'].unique())
print(df['classlabel'].unique())


['green' 'red' 'white' 'yellow' 'pink' 'black' 'grey' 'orange' 'lila'
 'blue']
['M' 'L' 'S' 'XL']
['sweatshirt' 't-shirt' 'pullover']


### 4.2. Mapping ordinal features

In [11]:
# define mapping dictionary S=1, M=2, L=3 and XL=4 and add size_code column to the dataset
size_mapping = {'XL': 4,
                'L': 3,
                'M': 2,
                'S': 1}
df['size_code'] = df['size'].map(size_mapping)


In [13]:
# define inverse mapping function
inv_size_mapping = {v: k for k, v in size_mapping.items()}
df['size_code'].map(inv_size_mapping)

0      M
1      L
2      S
3      M
4      M
5      S
6      S
7      S
8      L
9      M
10     L
11    XL
Name: size_code, dtype: object

In [15]:
# ind out inv size mapping dictonary
print(inv_size_mapping)

{4: 'XL', 3: 'L', 2: 'M', 1: 'S'}


### 4.3. Encoding class labels

In [21]:
from sklearn.preprocessing import LabelEncoder

# Label encoding with sklearn's LabelEncoder
Enc = LabelEncoder()
y = Enc.fit_transform(df['classlabel'].values)
y

array([1, 2, 2, 1, 1, 2, 2, 0, 2, 0, 0, 0])

In [23]:
# reverse mapping
Enc.inverse_transform(y)

array(['sweatshirt', 't-shirt', 't-shirt', 'sweatshirt', 'sweatshirt',
       't-shirt', 't-shirt', 'pullover', 't-shirt', 'pullover',
       'pullover', 'pullover'], dtype=object)

### 4.4. Performing one-hot encoding on nominal features

In [27]:
# encode the color column using LabelEncoder
y = Enc.fit_transform(df['color'].values)
y

array([2, 7, 8, 9, 6, 0, 3, 3, 3, 5, 4, 1])

In [31]:
# One hot encode the color column
from sklearn.preprocessing import OneHotEncoder

X = df[['color', 'size', 'price']].values
color_ohe = OneHotEncoder()
color_ohe.fit_transform(X[:, 0].reshape(-1, 1)).toarray()


array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
# one-hot encoding via pandas get_dummies
pd.get_dummies(df[['color', 'size', 'price']])

price  color_black  color_blue  color_green  color_grey  color_lila  \
0    10.1        False       False         True       False       False   
1    13.5        False       False        False       False       False   
2    13.5        False       False        False       False       False   
3    13.5        False       False        False       False       False   
4    13.5        False       False        False       False       False   
5    13.5         True       False        False       False       False   
6    13.5        False       False        False        True       False   
7    13.5        False       False        False        True       False   
8    13.5        False       False        False        True       False   
9    13.5        False       False        False       False       False   
10   13.5        False       False        False       False        True   
11   15.3        False        True        False       False       False   

    color_orange  color_pink  color_red  color_white  color_yellow  size_L  \
0          False       False      False        False         False   False   
1          False       False       True        False         False    True   
2          False       False      False         True         False   False   
3          False       False      False        False          True   False   
4          False        True      False        False         False   False   
5          False       False      False        False         False   False   
6          False       False      False        False         False   False   
7          False       False      False        False         False   False   
8          False       False      False        False         False    True   
9           True       False      False        False         False   False   
10         False       False      False        False         False    True   
11         False       False      False        False         False   False   

    size_M  size_S  size_XL  
0     True   False    False  
1    False   False    False  
2    False    True    False  
3     True   False    False  
4     True   False    False  
5    False    True    False  
6    False    True    False  
7    False    True    False  
8    False   False    False  
9     True   False    False  
10   False   False    False  
11   False   False     True

In [ ]:
# multicollinearity guard in get_dummies
# Multicollinearity arises when two or more variables in a regression are highly correlated
# removes the 1st categorial value (black is now a row with all the other colors as zero)
# (Note! dropping the first dummy variable can also lead to a slight loss in interpretability, 
# as you'll have to infer the dropped category based on the values of the remaining columns.)


## 5.0 Partitioning a dataset into a seperate training and test set

In [ ]:
# Read the wine dataset
# https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data
# df_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header=None)

# if the Wine dataset is temporarily unavailable from the
# UCI machine learning repository, un-comment the following line
# of code to load the dataset from a local path:

# df_wine = pd.read_csv('wine.data', header=None)

df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium', 'Total phenols',
                   'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                   'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                   'Proline']

print('Class labels', np.unique(df_wine['Class label']))
df_wine.head()

In [ ]:
# get wine dataset overview


In [ ]:
# find out unique classes


In [ ]:
# Create training and test datasets (ensure that distributions are preserved)
from sklearn.model_selection import train_test_split

X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0].values

X_train, X_test, y_train, y_test = train_test_split(X, y, 
    test_size=0.3, random_state=0, stratify=y)
print("Shapes: {} = {} + {}".format(X.shape, X_train.shape, X_test.shape))

## 6.0 Bringing features onto the same scale

In [ ]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

In [ ]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

## 7.0 Selecting meaningful features

Assessing feature importance with Random Forests

In [ ]:
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier

feat_labels = df_wine.columns[1:]
forest = RandomForestClassifier(n_estimators=10000, random_state=0, n_jobs=-1)

forest.fit(X_train, y_train)
importances = forest.feature_importances_

indices = np.argsort(importances)[::-1]

for f in range(X_train.shape[1]):
    print("%2d) %-*s %f" % (f + 1, 30, 
                            feat_labels[indices[f]], 
                            importances[indices[f]]))

plt.title('Feature Importance')
plt.bar(range(X_train.shape[1]), 
        importances[indices],
        align='center')

plt.xticks(range(X_train.shape[1]), 
           feat_labels[indices], rotation=90)
plt.xlim([-1, X_train.shape[1]])
plt.tight_layout()
#plt.savefig('images/04_09.png', dpi=300)
plt.show()

In [ ]:
from sklearn.feature_selection import SelectFromModel

sfm = SelectFromModel(forest, threshold=0.1, prefit=True)
X_selected = sfm.transform(X_train)
print('Number of features that meet this threshold criterion:', 
      X_selected.shape[1])

Print the 3 features that met the threshold criterion for feature selection that was set earlier 

In [ ]:
for f in range(X_selected.shape[1]):
    print("%2d) %-*s %f" % (f + 1, 30, 
                            feat_labels[indices[f]], 
                            importances[indices[f]]))